// MFCApplication4.idl : type library source for MFCApplication4.exe

// This file will be processed by the MIDL compiler to produce the
// type library (MFCApplication4.tlb).

[ uuid(2a2edf81-8cf6-44ce-9c96-cd97583e09cd), version(1.0) ]
library MFCApplication4
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for CMFCApplication4Doc

	[ uuid(5e8ec23a-84bd-46f4-ba6c-5e07f05a500a) ]
	dispinterface IMFCApplication4
	{
		properties:

		methods:
	};

	//  Class information for CMFCApplication4Doc

	[ uuid(57008ad8-a511-4146-b52e-4b557c606b46) ]
	coclass CMFCApplication4Doc
	{
		[default] dispinterface IMFCApplication4;
	};
};
